[project]
name = "mefic-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "firebase-admin>=6.7.0",
    "pydantic>=2.11.1",
    "yfinance>=0.2.55",
]
